In [36]:
import pandas as pd

dados = [
    ['MS', 13007.12, 'Centro-Oeste'],
    ['MA', 8452.03, 'Nordeste'],
    ['PA', 8289.86, 'Norte'],
    ['RR', 7700.47, 'Norte'],
    ['MT', 7343.44, 'Centro-Oeste'],
    ['PB', 6944.09, 'Nordeste'],
    ['RN', 6814.88, 'Nordeste'],
    ['AP', 6600.98, 'Norte'],
    ['DF', 6427.71, 'Centro-Oeste'],
    ['SE', 6176.76, 'Nordeste'],
    ['TO', 6130.70, 'Norte'],
    ['PE', 5841.91, 'Nordeste'],
    ['AL', 5767.15, 'Nordeste'],
    ['ES', 5685.97, 'Sudeste'],
    ['AM', 5631.18, 'Norte'],
    ['SP', 5565.00, 'Sudeste'],
    ['AC', 5370.35, 'Norte'],
    ['GO', 5160.49, 'Centro-Oeste'],
    ['RO', 5118.41, 'Norte'],
    ['RS', 5111.05, 'Sul'],
    ['SC', 5026.80, 'Sul'],
    ['PI', 4984.17, 'Nordeste'],
    ['BA', 4965.24, 'Nordeste'],
    ['CE', 4961.73, 'Nordeste'],
    ['PR', 4920.55, 'Sul'],
    ['MG', 4867.97, 'Sudeste']
]

df = pd.DataFrame(dados, columns=['UF', 'Salário inicial', 'Região'])

df.head()

   UF  Salário inicial        Região
0  MS         13007.12  Centro-Oeste
1  MA          8452.03      Nordeste
2  PA          8289.86         Norte
3  RR          7700.47         Norte
4  MT          7343.44  Centro-Oeste

In [39]:
estado_menor = df.loc[df['Salário inicial'].idxmin()]
estado_maior = df.loc[df['Salário inicial'].idxmax()]

print(f"MENOR salário: {estado_menor['UF']} (R$ {estado_menor['Salário inicial']:,.2f})")
print(f"MAIOR salário: {estado_maior['UF']} (R$ {estado_maior['Salário inicial']:,.2f})")

MENOR salário: MG (R$ 4,867.97)
MAIOR salário: MS (R$ 13,007.12)

In [41]:
df_rank = df.sort_values(by='Salário inicial', ascending=False).reset_index(drop=True)

posicao_go = df_rank[df_rank['UF'] == 'GO'].index[0] + 1

print(f"O estado de Goiás (GO) está na {posicao_go}ª posição.")

O estado de Goiás (GO) está na 18ª posição.

In [45]:
media_geral = df['Salário inicial'].mean()
print(f"Média salarial de TODOS os estados: R$ {media_geral:,.2f}")

Média salarial de TODOS os estados: R$ 6,264.08

In [48]:
tabela_regioes = df.groupby('Região')['Salário inicial'].agg(
    Média='mean',
    Maior='max',
    Menor='min'
).round(2)

tabela_regioes = tabela_regioes.sort_values(by='Média', ascending=False)

tabela_regioes

                Média     Maior    Menor
Região
Centro-Oeste  7984.69  13007.12  5160.49
Norte         6405.99   8289.86  5118.41
Nordeste      6100.88   8452.03  4961.73
Sudeste       5372.98   5685.97  4867.97
Sul           5019.47   5111.05  4920.55

In [50]:
regiao_maior_media = tabela_regioes['Média'].idxmax()
regiao_menor_media = tabela_regioes['Média'].idxmin()

print(f"Região com MAIOR média: {regiao_maior_media}")
print(f"Região com MENOR média: {regiao_menor_media}")

Região com MAIOR média: Centro-Oeste
Região com MENOR média: Sul

In [51]:
df

    UF  Salário inicial        Região
0   MS         13007.12  Centro-Oeste
1   MA          8452.03      Nordeste
2   PA          8289.86         Norte
3   RR          7700.47         Norte
4   MT          7343.44  Centro-Oeste
5   PB          6944.09      Nordeste
6   RN          6814.88      Nordeste
7   AP          6600.98         Norte
8   DF          6427.71  Centro-Oeste
9   SE          6176.76      Nordeste
10  TO          6130.70         Norte
11  PE          5841.91      Nordeste
12  AL          5767.15      Nordeste
13  ES          5685.97       Sudeste
14  AM          5631.18         Norte
15  SP          5565.00       Sudeste
16  AC          5370.35         Norte
17  GO          5160.49  Centro-Oeste
18  RO          5118.41         Norte
19  RS          5111.05           Sul
20  SC          5026.80           Sul
21  PI          4984.17      Nordeste
22  BA          4965.24      Nordeste
23  CE          4961.73      Nordeste
24  PR          4920.55           Sul
25  MG          4867.97       Sudeste